default_platform(:ios)

platform :ios do
  desc "Upload metadata and screenshots to App Store Connect"
  lane :upload_metadata do
    deliver(
      app_identifier: "com.biopoint.app",
      skip_binary_upload: true,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true,
      api_key_path: "./fastlane/asc_api_key.json",
      metadata_path: "./fastlane/metadata",
      screenshots_path: "./fastlane/metadata/en-US/screenshots",
    )
  end
end
